services:
  mongo:
    image: mongo:7.0.14
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - 27017:27017
    container_name: p-stats-mongo
    volumes:
      - ./mongo_data:/data/db
  
volumes:
  mongo_data: